sonar.projectKey=Adrian609_cloudvault-web
sonar.organization=adrian609
sonar.projectName=CloudVault Web
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11,3.12

sonar.sources=app.py,static,templates
sonar.tests=tests
sonar.exclusions=venv/**,.venv/**,__pycache__/**,.pytest_cache/**,.pytest_tmp/**,.ruff_cache/**,pytest-cache-files-*/**,.tmp-pip-audit/**,instance/**,uploads/**,docs/**,coverage.xml,test-results.xml,bandit-report.json,pip-audit-report.json,server.log
sonar.coverage.exclusions=tests/**,templates/**,static/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
